In [ ]:
# importing needed libraries

import numpy as np 
import pandas as pd

In [ ]:
# Importing the data

df1 = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/Data/df_cases_200906.gzip')
df2 = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/Data/df_label_200906.gzip')

In [ ]:
# Shape of both dataset

print(df1.shape)
print(df2.shape)

(2069, 8)
(1098, 3)

In [ ]:
# Printing a small portion of the data

df1.head()

,CaseId,FileName,Language,StartDate,DocumentType,IsExecuted,OcrText,QualityScore,ValidFileNames,InvalidFileNames
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,EN,20191104,Order form,False,Pressure style response character.,0.649292,,003061226227_12045631_Order form_978-1-67767-3...
1,003061226383,003061226383_63912371_Contract Info Pack_978-0...,EN,20190805,Contract Info Pack,False,Soon especially boy thousand traditional.,0.873038,,003061226383_63912371_Contract Info Pack_978-0...
2,003061226383,003061226383_41775424_other documents_978-1-38...,EN,20190805,other documents,True,Tax south say strategy hard between late.,0.991280,,003061226383_41775424_other documents_978-1-38...
3,003061227777,003061227777_96463321_other documents_978-1-96...,EN,20191231,other documents,False,Yet arm six design.,0.607833,,003061227777_96463321_other documents_978-1-96...
4,003061227781,003061227781_62201704_other documents_978-1-04...,EN,20191231,other documents,False,Plan camera actually run push rest.,0.909359,,003061227781_62201704_other documents_978-1-04...

In [ ]:
df2.head()

         CaseId label_1 label_2
0  003061226227   False   False
1  003061226383    True   False
2  003061227777   False   False
3  003061227781   False   False
4  003061227680    True    True

In [ ]:
# count of unique values in each column

df1.nunique()

CaseId          1098
FileName        2069
Language           1
StartDate        173
DocumentType      15
IsExecuted         2
OcrText         2069
QualityScore    2069
dtype: int64

In [ ]:
df2.nunique()

CaseId     1098
label_1       2
label_2       2
dtype: int64

In [ ]:
df1_copy = df1

In [ ]:
print(df1_copy.shape)
df1_copy.head()

(2069, 10)

,CaseId,FileName,Language,StartDate,DocumentType,IsExecuted,OcrText,QualityScore,ValidFileNames,InvalidFileNames
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,EN,20191104,Order form,False,Pressure style response character.,0.649292,,003061226227_12045631_Order form_978-1-67767-3...
1,003061226383,003061226383_63912371_Contract Info Pack_978-0...,EN,20190805,Contract Info Pack,False,Soon especially boy thousand traditional.,0.873038,,003061226383_63912371_Contract Info Pack_978-0...
2,003061226383,003061226383_41775424_other documents_978-1-38...,EN,20190805,other documents,True,Tax south say strategy hard between late.,0.991280,,003061226383_41775424_other documents_978-1-38...
3,003061227777,003061227777_96463321_other documents_978-1-96...,EN,20191231,other documents,False,Yet arm six design.,0.607833,,003061227777_96463321_other documents_978-1-96...
4,003061227781,003061227781_62201704_other documents_978-1-04...,EN,20191231,other documents,False,Plan camera actually run push rest.,0.909359,,003061227781_62201704_other documents_978-1-04...

**Adding new columns:**

 (1) ValidFileNames  	- List of all valid file names

 (2) InvalidFileNames	- List of all invalid file names

In [ ]:
%%time

df1_copy['ValidFileNames'] = ""
df1_copy['InvalidFileNames'] = ""

CPU times: user 501 µs, sys: 0 ns, total: 501 µs
Wall time: 510 µs

In [ ]:
print(df1_copy.shape)
df1_copy.head()

(2069, 10)

,CaseId,FileName,Language,StartDate,DocumentType,IsExecuted,OcrText,QualityScore,ValidFileNames,InvalidFileNames
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,EN,20191104,Order form,False,Pressure style response character.,0.649292,,
1,003061226383,003061226383_63912371_Contract Info Pack_978-0...,EN,20190805,Contract Info Pack,False,Soon especially boy thousand traditional.,0.873038,,
2,003061226383,003061226383_41775424_other documents_978-1-38...,EN,20190805,other documents,True,Tax south say strategy hard between late.,0.991280,,
3,003061227777,003061227777_96463321_other documents_978-1-96...,EN,20191231,other documents,False,Yet arm six design.,0.607833,,
4,003061227781,003061227781_62201704_other documents_978-1-04...,EN,20191231,other documents,False,Plan camera actually run push rest.,0.909359,,

**Contracts are considered INVALID below conditions satisfied:**

(1) IsExecuted == False

(2) QualityScore < 0.81

In [ ]:
%%time


for ind in df1_copy.index:

  contract = df1_copy["FileName"][ind]

  if (df1_copy["IsExecuted"][ind]) == False or (df1_copy["QualityScore"][ind]) < 0.81:
    df1_copy["InvalidFileNames"][ind] = contract

  else:
    df1_copy["ValidFileNames"][ind] = contract

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

CPU times: user 845 ms, sys: 82.6 ms, total: 928 ms
Wall time: 822 ms

In [ ]:
print(df1_copy.shape)
df1_copy.head()

(2069, 10)

,CaseId,FileName,Language,StartDate,DocumentType,IsExecuted,OcrText,QualityScore,ValidFileNames,InvalidFileNames
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,EN,20191104,Order form,False,Pressure style response character.,0.649292,,003061226227_12045631_Order form_978-1-67767-3...
1,003061226383,003061226383_63912371_Contract Info Pack_978-0...,EN,20190805,Contract Info Pack,False,Soon especially boy thousand traditional.,0.873038,,003061226383_63912371_Contract Info Pack_978-0...
2,003061226383,003061226383_41775424_other documents_978-1-38...,EN,20190805,other documents,True,Tax south say strategy hard between late.,0.991280,003061226383_41775424_other documents_978-1-38...,
3,003061227777,003061227777_96463321_other documents_978-1-96...,EN,20191231,other documents,False,Yet arm six design.,0.607833,,003061227777_96463321_other documents_978-1-96...
4,003061227781,003061227781_62201704_other documents_978-1-04...,EN,20191231,other documents,False,Plan camera actually run push rest.,0.909359,,003061227781_62201704_other documents_978-1-04...

In [ ]:
%%time


# Deleting unwanted columns
df = df1.drop(['FileName', 'Language', 'StartDate', 'DocumentType', 'IsExecuted', 'QualityScore'], axis=1)

CPU times: user 3.3 ms, sys: 0 ns, total: 3.3 ms
Wall time: 3.42 ms

In [ ]:
print(df.shape)
df.head()

(2069, 4)

,CaseId,OcrText,ValidFileNames,InvalidFileNames
0,003061226227,Pressure style response character.,,003061226227_12045631_Order form_978-1-67767-3...
1,003061226383,Soon especially boy thousand traditional.,,003061226383_63912371_Contract Info Pack_978-0...
2,003061226383,Tax south say strategy hard between late.,003061226383_41775424_other documents_978-1-38...,
3,003061227777,Yet arm six design.,,003061227777_96463321_other documents_978-1-96...
4,003061227781,Plan camera actually run push rest.,,003061227781_62201704_other documents_978-1-04...

In [ ]:
%%time


# Assigning Labels to df

for i in df["CaseId"]:
  for j in df2["CaseId"]:

    if i == j:
      
      df["label_1"] = df2["label_1"]
      df["label_2"] = df2["label_2"]

CPU times: user 1.72 s, sys: 0 ns, total: 1.72 s
Wall time: 1.71 s

In [ ]:
print(df.shape)
df.head()

(2069, 6)

,CaseId,OcrText,ValidFileNames,InvalidFileNames,label_1,label_2
0,003061226227,Pressure style response character.,,003061226227_12045631_Order form_978-1-67767-3...,False,False
1,003061226383,Soon especially boy thousand traditional.,,003061226383_63912371_Contract Info Pack_978-0...,True,False
2,003061226383,Tax south say strategy hard between late.,003061226383_41775424_other documents_978-1-38...,,False,False
3,003061227777,Yet arm six design.,,003061227777_96463321_other documents_978-1-96...,False,False
4,003061227781,Plan camera actually run push rest.,,003061227781_62201704_other documents_978-1-04...,True,True

In [ ]:
# Saving final prepared dataset : " df_final.gzip "


df.to_pickle('df_final.gzip')